### ISSUE TITLE
Bootstrap fails without subdir-object option.

### ISSUE THREAD

**Issue by DThiebaud** [aidin36/tocc#124]
For libtocc/test, ./bootstrap fails unless subdir-objects is added to AC_INIT_AUTOMAKE.

**Comment by DThiebaud** [comment]
Ubuntu 21.10

**Comment by aidin36** [comment]
On Ubuntu 20.04, it just gives warnings but works fine.
Feel free to send a PR with the added option. I will test and if it was working on 20.04 too, I'll merge it.

**Comment by DThiebaud** [comment]
I was mistaken, this works as written.
